apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: namespace-workflow-1708566228128
spec:
  type: LoadBalancer
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000